"""Build a `RepoMap`: a compact summary of the target repo's structure.

A RepoMap is what we inject into LLM prompts in place of "here is the
whole repo." It contains:
- The package tree (every directory containing .go files)
- For each package: a one-line purpose (from the package-level doc comment)
- For each exported symbol: file + signature line

This is generated by walking the filesystem and parsing Go files. We do
NOT use go tools here (don't want to require gopls) — a regex/AST-lite
pass is enough for the prompt.

We cache the map per (repo, commit-sha) at `.goagent/repo_map.json` inside
the workspace, so repeated runs on the same commit skip the walk.
"""
from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from agent.config import RepoConfig
from agent.tools.shell import git_head_sha


_PACKAGE_RE = re.compile(r"^package\s+(\w+)", re.MULTILINE)
_DOC_RE = re.compile(r"^//\s?(.*)$", re.MULTILINE)
_FUNC_RE = re.compile(
    r"^func\s+(?:\([^)]+\)\s+)?([A-Z]\w*)\s*\(", re.MULTILINE
)
_TYPE_RE = re.compile(r"^type\s+([A-Z]\w*)\s+", re.MULTILINE)
_VAR_RE = re.compile(r"^(?:var|const)\s+([A-Z]\w*)", re.MULTILINE)


@dataclass
class Symbol:
    name: str
    kind: str   # "func" | "type" | "var" | "const"
    file: str   # relative to repo root
    line: int

    def to_dict(self) -> dict[str, Any]:
        return {"name": self.name, "kind": self.kind, "file": self.file, "line": self.line}


@dataclass
class Package:
    path: str            # relative to repo root, e.g. "cmd/foo"
    go_package: str      # the actual `package X` declaration
    doc: str = ""        # one-line summary
    files: list[str] = field(default_factory=list)
    symbols: list[Symbol] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path, "go_package": self.go_package, "doc": self.doc,
            "files": self.files,
            "symbols": [s.to_dict() for s in self.symbols],
        }


@dataclass
class RepoMap:
    repo_slug: str
    commit_sha: str
    packages: list[Package]
    file_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "repo_slug": self.repo_slug,
            "commit_sha": self.commit_sha,
            "file_count": self.file_count,
            "packages": [p.to_dict() for p in self.packages],
        }

    def short_summary(self, max_chars: int = 8000) -> str:
        """A human-readable, token-frugal rendering for prompt injection."""
        lines = [f"# Repo map: {self.repo_slug} @ {self.commit_sha[:8]}", ""]
        for pkg in self.packages:
            lines.append(f"## {pkg.path or '/'}  (package {pkg.go_package})")
            if pkg.doc:
                lines.append(f"  {pkg.doc}")
            for s in pkg.symbols[:30]:  # cap per package
                lines.append(f"  - {s.kind} {s.name}  [{s.file}:{s.line}]")
            lines.append("")
        out = "\n".join(lines)
        if len(out) > max_chars:
            out = out[:max_chars] + "\n... (truncated)\n"
        return out


def _is_ignored(rel_path: str, ignore_globs: list[str]) -> bool:
    from fnmatch import fnmatch
    return any(fnmatch(rel_path, g) for g in ignore_globs)


def _extract_package_doc(text: str) -> str:
    """Return the first contiguous block of `//` comments at top of file."""
    out: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("//"):
            out.append(line[2:].strip())
        elif line and not line.startswith("//"):
            break
    joined = " ".join(out).strip()
    return joined[:200]


def index_repo(workspace: Path, cfg: RepoConfig) -> RepoMap:
    cache_dir = workspace / ".goagent"
    cache_dir.mkdir(parents=True, exist_ok=True)
    sha = git_head_sha(workspace)
    cache_file = cache_dir / f"repo_map_{sha[:12]}.json"
    if cache_file.exists():
        raw = json.loads(cache_file.read_text(encoding="utf-8"))
        return _from_dict(raw)

    packages: dict[str, Package] = {}
    file_count = 0
    for path in workspace.rglob("*.go"):
        rel = path.relative_to(workspace).as_posix()
        if _is_ignored(rel, cfg.ignore_globs):
            continue
        if "_test.go" in path.name:
            # Skip test files in the map — too noisy. Test files are still
            # readable via tools at retrieval time.
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        file_count += 1
        pkg_match = _PACKAGE_RE.search(text)
        if not pkg_match:
            continue
        go_pkg = pkg_match.group(1)
        dir_rel = str(path.parent.relative_to(workspace).as_posix())
        if dir_rel == ".":
            dir_rel = ""
        pkg = packages.get(dir_rel)
        if pkg is None:
            pkg = Package(path=dir_rel, go_package=go_pkg, doc=_extract_package_doc(text))
            packages[dir_rel] = pkg
        pkg.files.append(rel)
        # Quick symbol extraction. We use line numbers from the original text.
        for m in _FUNC_RE.finditer(text):
            line = text[:m.start()].count("\n") + 1
            pkg.symbols.append(Symbol(name=m.group(1), kind="func", file=rel, line=line))
        for m in _TYPE_RE.finditer(text):
            line = text[:m.start()].count("\n") + 1
            pkg.symbols.append(Symbol(name=m.group(1), kind="type", file=rel, line=line))
        for m in _VAR_RE.finditer(text):
            line = text[:m.start()].count("\n") + 1
            pkg.symbols.append(Symbol(name=m.group(1), kind="var", file=rel, line=line))

    rm = RepoMap(
        repo_slug=cfg.slug,
        commit_sha=sha,
        packages=sorted(packages.values(), key=lambda p: p.path),
        file_count=file_count,
    )
    cache_file.write_text(json.dumps(rm.to_dict(), indent=2), encoding="utf-8")
    return rm


def _from_dict(raw: dict[str, Any]) -> RepoMap:
    pkgs = []
    for p in raw["packages"]:
        pkgs.append(Package(
            path=p["path"], go_package=p["go_package"], doc=p.get("doc", ""),
            files=p["files"],
            symbols=[Symbol(**s) for s in p["symbols"]],
        ))
    return RepoMap(
        repo_slug=raw["repo_slug"], commit_sha=raw["commit_sha"],
        packages=pkgs, file_count=raw["file_count"],
    )
